@extends('layouts.participants.master')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Terms and conditions</div>

                    <div class="panel-body">
                        <p style="line-height: 2.0571514285714287; margin-top: 0pt; margin-bottom: 11pt;"><span style="font-size: 10.5pt; font-family: Arial; color: #434343; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">The Crete Trip 2018 by ESN Greece </span></p>
                        <p style="line-height: 2.0571514285714287; margin-top: 0pt; margin-bottom: 11pt;"><span style="font-size: 10.5pt; font-family: Arial; color: #434343; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Terms &amp; Conditions</span></p>
                        <p style="line-height: 2.0571514285714287; margin-top: 0pt; margin-bottom: 11pt;"><span style="font-size: 10.5pt; font-family: Arial; color: #434343; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">10/05/2018 &ndash; 13/05/2018 </span></p>
                        <p style="line-height: 2.0571514285714287; margin-top: 0pt; margin-bottom: 11pt;"><span style="font-size: 10.5pt; font-family: Arial; color: #434343; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">I hereby agree that ESN Greece does not assume any responsibility whatsoever for any damage that a participant of a trip or activity arranged by ESN may cause to either the ESN or any third parties (i.e. travel companies, boats, hostels, hotels etc.). Every entity, including ESN Greece, has the right to seek reparation for any damage that a participant may cause.</span></p>
                        <p style="line-height: 2.0571514285714287; margin-top: 0pt; margin-bottom: 11pt;"><span style="font-size: 10.5pt; font-family: Arial; color: #434343; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">I also understand and accept that neither ESN Greece, nor the sponsors, university officials, volunteers or anyone involved or affiliated with the event in any way, can be held responsible for any injuries, death or other damage that may occur to a participant or his/her heirs, or related to his/her people or entities, as a result of the participant&rsquo;s participation in the trip/excursion or as a result of either active or passive negligence of any person.</span></p>
                        <p style="line-height: 2.0571514285714287; margin-top: 0pt; margin-bottom: 11pt;"><span style="font-size: 10.5pt; font-family: Arial; color: #434343; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">I understand that the Organizing Committee is not responsible for any personal lost items during the event.</span></p>
                        <p style="line-height: 2.0571514285714287; margin-top: 0pt; margin-bottom: 11pt;"><span style="font-size: 10.5pt; font-family: Arial; color: #434343; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">I understand that the Organizing Committee reserves the right to amend or modify any part of the event content or/and schedule if necessary, at any time.</span></p>
                        <p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;"><span style="font-size: 10.5pt; font-family: Arial; color: #434343; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">I shall respect the transport schedule established by the organisers, including departure times and bus assignments. The OC is not responsible for any participant&rsquo;s transport and accommodation beyond the official programme, either before or after the announced event dates.</span></p>
                        <p style="line-height: 2.0571514285714287; margin-top: 0pt; margin-bottom: 11pt;">&nbsp;</p>
                        <p style="line-height: 2.0571514285714287; margin-top: 0pt; margin-bottom: 11pt;"><span style="font-size: 10.5pt; font-family: Arial; color: #434343; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">I also agree that I am not entitled to any refund from pre-paid activities included in the event fee, once payment has been made. </span></p>
                        <p style="line-height: 2.0571514285714287; margin-top: 0pt; margin-bottom: 11pt;"><span style="font-size: 10.5pt; font-family: Arial; color: #434343; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Furthermore, I take full responsibility if I decide not to travel with or use any pre-booked transportation (bus or ferry). If a participant fails to attend any pre-paid activity or misses any pre-booked transportation, no refund or compensation will be paid by ESN or anyone else. In the event of an accident requiring additional professional care, such as an ambulance or hospital, you must contact your ESN group leaders for further instructions.</span></p>
                        <p style="line-height: 2.0571514285714287; margin-top: 0pt; margin-bottom: 11pt;"><span style="font-size: 10.5pt; font-family: Arial; color: #434343; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">The OC has the right to expel anyone who is causing troubles during the event and is not following the given rules.</span></p>
                        <p style="line-height: 2.0571514285714287; margin-top: 0pt; margin-bottom: 11pt;"><span style="font-size: 10.5pt; font-family: Arial; color: #434343; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">ESN Greece has my full consent to store my personal data submitted through the event registration form, to give every participant access to systems that show their registration process and offer advanced rooming capabilities. ESN Greece will NOT share any of your personal data with external sources or use any of the data acquired from the registration form for advertising purposes.</span></p>
                        <p style="line-height: 2.0571514285714287; margin-top: 0pt; margin-bottom: 11pt;"><span style="font-size: 10.5pt; font-family: Arial; color: #434343; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Finally, I hereby give full rights to ESN Greece to use my image in films, videos, photographs and any further elaborated form of the previous as well as my name and my voice, for the purposes of promotion, advertising, training manuals and volunteering in every part of the world in any medium and in any time, without any restrictions.</span></p>
                        <p style="line-height: 2.0571514285714287; margin-top: 0pt; margin-bottom: 11pt;"><span style="font-size: 10.5pt; font-family: Arial; color: #434343; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Remember, you are responsible for your actions! </span></p>
                        <p style="line-height: 2.0571514285714287; margin-top: 0pt; margin-bottom: 11pt;"><span style="font-size: 10.5pt; font-family: Arial; color: #434343; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">All formalities aside and most importantly&hellip; &nbsp;ENJOY The Crete Trip!!</span></p>
                        <p style="line-height: 2.0571514285714287; margin-top: 0pt; margin-bottom: 11pt;"><br /><br /><br /><br /></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection